repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: prometheus
    namespace: monitoring
    createNamespace: true
    disableValidationOnInstall: true
    chart: prometheus-community/kube-prometheus-stack
    values:
      - ../values/kube-prometheus-stack.yaml
